//! Claude byte-BPE token counting, ported from `ai-tokenizer`'s `claude` encoding so Rust
//! and the TypeScript harness agree on budget math.
//!
//! The reference is `Tokenizer(claudeEncoding).encode(text, "all").length`. In `"all"` mode
//! special-token strings such as `<EOT>` are ordinary text, so they encode as their bytes
//! rather than as one reserved rank. This crate therefore builds `CoreBPE` with an empty
//! special-token table and only exposes the `_ordinary` paths. `tests/token_golden.rs` pins
//! the token ids against a corpus generated by the TypeScript implementation.
//!
//! The pattern rewrites upstream `\s`/`\S` as explicit classes because ECMAScript and Rust
//! define `\s` differently: ECMAScript includes U+FEFF and excludes U+0085; the `regex` crate
//! includes U+0085 and excludes U+FEFF. `assets/claude.pat` holds the upstream pattern; a unit
//! test derives `CLAUDE_PAT_STR` from it to detect drift.
//!
//! `ai-tokenizer@1.0.6` has two bugs that produce ids decoding to different bytes than the
//! input. Reproducing them would make counts wrong rather than merely different, so this crate
//! encodes those inputs correctly and diverges from the reference there:
//!
//! * The reference's rank lookup indexes a plain object, so a pre-token equal to an
//!   `Object.prototype` member name that is not a vocabulary entry (`valueOf`,
//!   `hasOwnProperty`, `isPrototypeOf`, `toLocaleString`, `propertyIsEnumerable`) yields a
//!   function instead of a rank and is emitted as one "token". `gen/gen-token-golden.ts`
//!   hands the tokenizer a null-prototype copy of the encoder, so the golden corpus pins the
//!   correct ids.
//! * The reference's BPE rank lookup decodes candidate byte slices with a `TextDecoder` that
//!   strips a leading BOM, so a slice starting with `EF BB BF` is scored as if the BOM were
//!   absent and `"x\u{feff}\n"` encodes to two ids with the BOM gone. The golden test pins the
//!   Rust ids for `"x\u{feff}\n"`.
//!
//! tiktoken's merge loop is quadratic in the byte length of one pre-token piece, and
//! ` ?\p{L}+` makes a piece as long as the longest run of letters (37k CJK characters with no
//! punctuation take seconds). Pieces longer than [`MAX_PIECE_BYTES`] are split at character
//! boundaries into chunks of at most that size before merging, which bounds the cost to
//! `O(len * MAX_PIECE_BYTES)`. Ids for such pieces can differ from the reference by a few
//! seam tokens; every piece at or below the cap is encoded exactly as the reference does.
#![warn(missing_docs)]

mod bpe;
#[cfg(test)]
mod parity_tests;
#[cfg(test)]
mod reference_impl;
mod scan;
#[cfg(test)]
mod unicode_gen_tests;
mod unicode_tables;
#[cfg(test)]
mod vocab_blob_tests;

use std::sync::OnceLock;

/// Token id type; `u32`, the same as `tiktoken_rs::Rank`.
pub type Rank = u32;

/// Vocabulary decoded by `build.rs` from `assets/claude.tiktoken` (layout documented there),
/// embedded so counting needs no file or network.
const VOCAB_BLOB: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/vocab.bin"));

/// The unit tests derive [`CLAUDE_PAT_STR`] from this upstream pattern.
#[cfg(test)]
const UPSTREAM_PAT_STR: &str = include_str!("../assets/claude.pat");

/// Contents of the ECMAScript `\s` class (WhiteSpace + LineTerminator). Differs from the
/// `regex` crate's `\s` by including U+FEFF and excluding U+0085.
#[cfg(test)]
macro_rules! ecmascript_whitespace {
    () => {
        r"\t\n\x0B\x0C\r \x{00A0}\x{1680}\x{2000}-\x{200A}\x{2028}\x{2029}\x{202F}\x{205F}\x{3000}\x{FEFF}"
    };
}

/// Pre-tokenizer pattern that [`scan`] implements by hand; text is split on these boundaries
/// and BPE merges run separately within each piece. The pattern substitutes the ECMAScript
/// whitespace class for upstream `\s` and `\S`. A unit test asserts equality with
/// `reference_impl::CLAUDE_PAT_STR`, the oracle the scanner is tested against.
#[cfg(test)]
const CLAUDE_PAT_STR: &str = concat!(
    r"'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^",
    ecmascript_whitespace!(),
    r"\p{L}\p{N}]+|[",
    ecmascript_whitespace!(),
    r"]+(?![^",
    ecmascript_whitespace!(),
    r"])|[",
    ecmascript_whitespace!(),
    r"]+",
);

/// Longest pre-token piece that is merged whole. Longer pieces are chunked at character
/// boundaries; see the crate docs. Real text almost never produces a piece this long, so
/// parity with the reference holds in practice while worst-case latency stays linear.
pub const MAX_PIECE_BYTES: usize = 4096;

fn vocab() -> &'static bpe::Vocab {
    static VOCAB: OnceLock<bpe::Vocab> = OnceLock::new();
    VOCAB.get_or_init(|| bpe::Vocab::from_blob(VOCAB_BLOB))
}

/// Splits `piece` into chunks of at most `max_bytes` on `char` boundaries.
fn char_chunks(piece: &str, max_bytes: usize) -> impl Iterator<Item = &str> {
    let mut rest = piece;
    std::iter::from_fn(move || {
        if rest.is_empty() {
            return None;
        }
        let mut end = rest.len().min(max_bytes);
        while !rest.is_char_boundary(end) {
            end -= 1;
        }
        let (head, tail) = rest.split_at(end);
        rest = tail;
        Some(head)
    })
}

/// Encodes `text`, chunking any pre-token piece longer than [`MAX_PIECE_BYTES`].
fn encode_bounded(text: &str) -> Vec<Rank> {
    let vocab = vocab();
    let mut out = Vec::new();
    let mut scratch = bpe::Scratch::default();
    let bytes = text.as_bytes();
    for (start, end) in scan::pieces(text) {
        if end - start <= MAX_PIECE_BYTES {
            vocab.encode_piece(bytes, start, end, &mut scratch, &mut out);
        } else {
            let mut at = start;
            for chunk in char_chunks(&text[start..end], MAX_PIECE_BYTES) {
                vocab.encode_piece(bytes, at, at + chunk.len(), &mut scratch, &mut out);
                at += chunk.len();
            }
        }
    }
    out
}

/// Token count of `text` under the Claude encoding; zero for empty input.
///
/// Equal to `encode_ordinary(text).len()`. Work is bounded per pre-token piece; see
/// [`MAX_PIECE_BYTES`].
pub fn estimate_tokens(text: &str) -> usize {
    encode_bounded(text).len()
}

/// Token ids of `text`. Same ids `ai-tokenizer` produces except for the reference defects and
/// over-long pieces described in the crate docs; used by the golden test.
pub fn encode_ordinary(text: &str) -> Vec<Rank> {
    encode_bounded(text)
}

#[cfg(test)]
mod tests {
    use fancy_regex::Regex;

    use super::*;

    /// `CLAUDE_PAT_STR` must be exactly the upstream pattern with the ECMAScript whitespace
    /// class substituted for `\s`/`\S`. If upstream changes `pat_str`, regenerating the sidecar
    /// makes this fail until the constant is updated.
    #[test]
    fn pattern_is_upstream_with_ecmascript_whitespace() {
        let upstream = UPSTREAM_PAT_STR.trim_end_matches('\n');
        let ws = ecmascript_whitespace!();
        let derived = upstream
            .replace(r"[^\s", &format!("[^{ws}"))
            .replace(r"\S", &format!("[^{ws}]"))
            .replace(r"\s", &format!("[{ws}]"));
        assert_eq!(derived, CLAUDE_PAT_STR);
        assert!(!CLAUDE_PAT_STR.contains(r"\s"), "unexpanded \\s in pattern");
        assert!(!CLAUDE_PAT_STR.contains(r"\S"), "unexpanded \\S in pattern");
    }

    /// The scanner tests use `reference_impl`, not `CLAUDE_PAT_STR`, as their oracle; this
    /// equality is what lets the upstream check above reach the scanner.
    #[test]
    fn reference_pattern_equals_upstream_derived_pattern() {
        assert_eq!(reference_impl::CLAUDE_PAT_STR, CLAUDE_PAT_STR);
    }

    #[test]
    fn whitespace_class_matches_ecmascript_not_unicode_white_space() {
        let class = ecmascript_whitespace!();
        let ws = Regex::new(&format!("^[{class}]$")).unwrap();
        for c in [
            '\t', '\n', '\u{0B}', '\u{0C}', '\r', ' ', '\u{A0}', '\u{1680}', '\u{2000}',
            '\u{200A}', '\u{2028}', '\u{2029}', '\u{202F}', '\u{205F}', '\u{3000}', '\u{FEFF}',
        ] {
            assert!(
                ws.is_match(&c.to_string()).unwrap(),
                "{c:?} should be whitespace"
            );
        }
        for c in ['\u{85}', '\u{200B}', 'a', '\u{180E}'] {
            assert!(
                !ws.is_match(&c.to_string()).unwrap(),
                "{c:?} should not be whitespace"
            );
        }
    }

    #[test]
    fn char_chunks_respect_boundaries_and_cap() {
        let s = "é".repeat(5); // 10 bytes, 2 per char
        let chunks: Vec<&str> = char_chunks(&s, 3).collect();
        assert_eq!(chunks, vec!["é", "é", "é", "é", "é"]);
        let chunks: Vec<&str> = char_chunks("abcdefg", 3).collect();
        assert_eq!(chunks, vec!["abc", "def", "g"]);
        assert_eq!(char_chunks("", 3).count(), 0);
    }
}
