//! Claude byte-BPE token counting, ported from `ai-tokenizer`'s `claude` encoding so Rust
//! and the TypeScript harness agree on budget math.
//!
//! The reference is `Tokenizer(claudeEncoding).encode(text, "all").length`. In `"all"` mode
//! special-token strings such as `<EOT>` are ordinary text, so they encode as their bytes
//! rather than as one reserved rank. This crate therefore builds `CoreBPE` with an empty
//! special-token table and only exposes the `_ordinary` paths. `tests/token_golden.rs` pins
//! the token ids against a corpus generated by the TypeScript implementation.
#![warn(missing_docs)]

use std::sync::OnceLock;

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;
use rustc_hash::FxHashMap;
use tiktoken_rs::{CoreBPE, Rank};

/// Vocabulary as `<base64 token> <rank>` lines, embedded so counting needs no file or network.
const CLAUDE_TIKTOKEN: &str = include_str!("../assets/claude.tiktoken");

/// Pre-tokenizer regex; text is split on these boundaries before BPE merges run within each
/// piece. Must match the TypeScript encoding byte for byte or ids diverge.
const CLAUDE_PAT_STR: &str =
    r"'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+";

fn tokenizer() -> &'static CoreBPE {
    static TOKENIZER: OnceLock<CoreBPE> = OnceLock::new();
    TOKENIZER.get_or_init(|| {
        let mut encoder: FxHashMap<Vec<u8>, Rank> = FxHashMap::default();
        for line in CLAUDE_TIKTOKEN.lines() {
            if line.is_empty() {
                continue;
            }
            let mut parts = line.split(' ');
            let raw = parts.next().expect("vocab line missing token field");
            let rank_str = parts.next().expect("vocab line missing rank field");
            let bytes = STANDARD
                .decode(raw)
                .expect("vocab token is not valid base64");
            let rank: Rank = rank_str.parse().expect("vocab rank is not a u32");
            encoder.insert(bytes, rank);
        }
        CoreBPE::new(encoder, FxHashMap::default(), CLAUDE_PAT_STR)
            .expect("claude BPE construction failed (bad vocab or pattern)")
    })
}

/// Token count of `text` under the Claude encoding; zero for empty input.
pub fn estimate_tokens(text: &str) -> usize {
    if text.is_empty() {
        return 0;
    }
    tokenizer().count_ordinary(text)
}

/// Token ids of `text`. Same ids `ai-tokenizer` produces; used by the golden test.
pub fn encode_ordinary(text: &str) -> Vec<Rank> {
    tokenizer().encode_ordinary(text)
}
