//! Claude byte-BPE token counting, ported from `ai-tokenizer`'s `claude` encoding so Rust
//! and the TypeScript harness agree on budget math.
//!
//! The reference is `Tokenizer(claudeEncoding).encode(text, "all").length`. In `"all"` mode
//! special-token strings such as `<EOT>` are ordinary text, so they encode as their bytes
//! rather than as one reserved rank. This crate therefore builds `CoreBPE` with an empty
//! special-token table and only exposes the `_ordinary` paths. `tests/token_golden.rs` pins
//! the token ids against a corpus generated by the TypeScript implementation.
//!
//! The pattern rewrites upstream `\s`/`\S` as explicit classes because ECMAScript and Rust
//! define `\s` differently: ECMAScript includes U+FEFF and excludes U+0085; the `regex` crate
//! includes U+0085 and excludes U+FEFF. `assets/claude.pat` holds the upstream pattern; a unit
//! test derives `CLAUDE_PAT_STR` from it to detect drift.
//!
//! `ai-tokenizer@1.0.6` has two bugs that produce ids decoding to different bytes than the
//! input. Reproducing them would make counts wrong rather than merely different, so this crate
//! encodes those inputs correctly and diverges from the reference there:
//!
//! * The reference's rank lookup indexes a plain object, so a pre-token equal to an
//!   `Object.prototype` member name that is not a vocabulary entry (`valueOf`,
//!   `hasOwnProperty`, `isPrototypeOf`, `toLocaleString`, `propertyIsEnumerable`) yields a
//!   function instead of a rank and is emitted as one "token". `gen/gen-token-golden.ts`
//!   hands the tokenizer a null-prototype copy of the encoder, so the golden corpus pins the
//!   correct ids.
//! * The reference's BPE rank lookup decodes candidate byte slices with a `TextDecoder` that
//!   strips a leading BOM, so a slice starting with `EF BB BF` is scored as if the BOM were
//!   absent and `"x\u{feff}\n"` encodes to two ids with the BOM gone. The golden test pins the
//!   Rust ids for `"x\u{feff}\n"`.
//!
//! tiktoken's merge loop is quadratic in the byte length of one pre-token piece, and
//! ` ?\p{L}+` makes a piece as long as the longest run of letters (37k CJK characters with no
//! punctuation take seconds). Pieces longer than [`MAX_PIECE_BYTES`] are split at character
//! boundaries into chunks of at most that size before merging, which bounds the cost to
//! `O(len * MAX_PIECE_BYTES)`. Ids for such pieces can differ from the reference by a few
//! seam tokens; every piece at or below the cap is encoded exactly as the reference does.
#![warn(missing_docs)]

use std::sync::OnceLock;

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD;
use fancy_regex::Regex;
use rustc_hash::FxHashMap;
use tiktoken_rs::{CoreBPE, Rank};

/// Vocabulary as `<base64 token> <rank>` lines, embedded so counting needs no file or network.
const CLAUDE_TIKTOKEN: &str = include_str!("../assets/claude.tiktoken");

/// Upstream `pat_str`, written by `gen/gen-claude-vocab.ts`. Only the unit test reads it; the
/// runtime pattern is [`CLAUDE_PAT_STR`].
#[cfg(test)]
const UPSTREAM_PAT_STR: &str = include_str!("../assets/claude.pat");

/// Contents of the ECMAScript `\s` class (WhiteSpace + LineTerminator). Differs from the
/// `regex` crate's `\s` by including U+FEFF and excluding U+0085.
macro_rules! ecmascript_whitespace {
    () => {
        r"\t\n\x0B\x0C\r \x{00A0}\x{1680}\x{2000}-\x{200A}\x{2028}\x{2029}\x{202F}\x{205F}\x{3000}\x{FEFF}"
    };
}

/// Pre-tokenizer regex; text is split on these boundaries before BPE merges run within each
/// piece. Upstream `pat_str` with `\s` and `\S` replaced by the ECMAScript whitespace class.
const CLAUDE_PAT_STR: &str = concat!(
    r"'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^",
    ecmascript_whitespace!(),
    r"\p{L}\p{N}]+|[",
    ecmascript_whitespace!(),
    r"]+(?![^",
    ecmascript_whitespace!(),
    r"])|[",
    ecmascript_whitespace!(),
    r"]+",
);

/// Longest pre-token piece that is merged whole. Longer pieces are chunked at character
/// boundaries; see the crate docs. Real text almost never produces a piece this long, so
/// parity with the reference holds in practice while worst-case latency stays linear.
pub const MAX_PIECE_BYTES: usize = 4096;

fn tokenizer() -> &'static CoreBPE {
    static TOKENIZER: OnceLock<CoreBPE> = OnceLock::new();
    TOKENIZER.get_or_init(|| {
        let mut encoder: FxHashMap<Vec<u8>, Rank> = FxHashMap::default();
        for line in CLAUDE_TIKTOKEN.lines() {
            if line.is_empty() {
                continue;
            }
            let mut parts = line.split(' ');
            let raw = parts.next().expect("vocab line missing token field");
            let rank_str = parts.next().expect("vocab line missing rank field");
            let bytes = STANDARD
                .decode(raw)
                .expect("vocab token is not valid base64");
            let rank: Rank = rank_str.parse().expect("vocab rank is not a u32");
            encoder.insert(bytes, rank);
        }
        CoreBPE::new(encoder, FxHashMap::default(), CLAUDE_PAT_STR)
            .expect("claude BPE construction failed (bad vocab or pattern)")
    })
}

/// The same pattern `CoreBPE` uses, compiled once so over-long pieces can be located.
fn piece_regex() -> &'static Regex {
    static REGEX: OnceLock<Regex> = OnceLock::new();
    REGEX.get_or_init(|| Regex::new(CLAUDE_PAT_STR).expect("claude pattern failed to compile"))
}

/// Splits `piece` into chunks of at most `max_bytes` on `char` boundaries.
fn char_chunks(piece: &str, max_bytes: usize) -> impl Iterator<Item = &str> {
    let mut rest = piece;
    std::iter::from_fn(move || {
        if rest.is_empty() {
            return None;
        }
        let mut end = rest.len().min(max_bytes);
        while !rest.is_char_boundary(end) {
            end -= 1;
        }
        let (head, tail) = rest.split_at(end);
        rest = tail;
        Some(head)
    })
}

/// Encodes `text`, chunking any pre-token piece longer than [`MAX_PIECE_BYTES`]. Spans between
/// over-long pieces are handed to `CoreBPE` whole: they start and end on piece boundaries, so
/// re-running the pattern on a span yields the same pieces as running it on the full text.
fn encode_bounded(bpe: &CoreBPE, text: &str) -> Vec<Rank> {
    if text.len() <= MAX_PIECE_BYTES {
        return bpe.encode_ordinary(text);
    }
    let mut out = Vec::new();
    let mut span_start = 0;
    for m in piece_regex().find_iter(text) {
        let m = m.expect("claude pattern hit fancy-regex's backtrack limit");
        if m.end() - m.start() <= MAX_PIECE_BYTES {
            continue;
        }
        out.extend(bpe.encode_ordinary(&text[span_start..m.start()]));
        for chunk in char_chunks(m.as_str(), MAX_PIECE_BYTES) {
            out.extend(bpe.encode_ordinary(chunk));
        }
        span_start = m.end();
    }
    out.extend(bpe.encode_ordinary(&text[span_start..]));
    out
}

/// Token count of `text` under the Claude encoding; zero for empty input.
///
/// Equal to `encode_ordinary(text).len()`. Work is bounded per pre-token piece; see
/// [`MAX_PIECE_BYTES`].
pub fn estimate_tokens(text: &str) -> usize {
    if text.is_empty() {
        return 0;
    }
    encode_bounded(tokenizer(), text).len()
}

/// Token ids of `text`. Same ids `ai-tokenizer` produces except for the reference defects and
/// over-long pieces described in the crate docs; used by the golden test.
pub fn encode_ordinary(text: &str) -> Vec<Rank> {
    encode_bounded(tokenizer(), text)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `CLAUDE_PAT_STR` must be exactly the upstream pattern with the ECMAScript whitespace
    /// class substituted for `\s`/`\S`. If upstream changes `pat_str`, regenerating the sidecar
    /// makes this fail until the constant is updated.
    #[test]
    fn pattern_is_upstream_with_ecmascript_whitespace() {
        let upstream = UPSTREAM_PAT_STR.trim_end_matches('\n');
        let ws = ecmascript_whitespace!();
        let derived = upstream
            .replace(r"[^\s", &format!("[^{ws}"))
            .replace(r"\S", &format!("[^{ws}]"))
            .replace(r"\s", &format!("[{ws}]"));
        assert_eq!(derived, CLAUDE_PAT_STR);
        assert!(!CLAUDE_PAT_STR.contains(r"\s"), "unexpanded \\s in pattern");
        assert!(!CLAUDE_PAT_STR.contains(r"\S"), "unexpanded \\S in pattern");
    }

    #[test]
    fn whitespace_class_matches_ecmascript_not_unicode_white_space() {
        let class = ecmascript_whitespace!();
        let ws = Regex::new(&format!("^[{class}]$")).unwrap();
        for c in [
            '\t', '\n', '\u{0B}', '\u{0C}', '\r', ' ', '\u{A0}', '\u{1680}', '\u{2000}',
            '\u{200A}', '\u{2028}', '\u{2029}', '\u{202F}', '\u{205F}', '\u{3000}', '\u{FEFF}',
        ] {
            assert!(
                ws.is_match(&c.to_string()).unwrap(),
                "{c:?} should be whitespace"
            );
        }
        for c in ['\u{85}', '\u{200B}', 'a', '\u{180E}'] {
            assert!(
                !ws.is_match(&c.to_string()).unwrap(),
                "{c:?} should not be whitespace"
            );
        }
    }

    #[test]
    fn char_chunks_respect_boundaries_and_cap() {
        let s = "é".repeat(5); // 10 bytes, 2 per char
        let chunks: Vec<&str> = char_chunks(&s, 3).collect();
        assert_eq!(chunks, vec!["é", "é", "é", "é", "é"]);
        let chunks: Vec<&str> = char_chunks("abcdefg", 3).collect();
        assert_eq!(chunks, vec!["abc", "def", "g"]);
        assert_eq!(char_chunks("", 3).count(), 0);
    }
}
