//! `unicode_tables.rs` must equal what `regex-syntax` (the crate behind the reference pattern's
//! `\p{L}` / `\p{N}`) defines. `cargo test -p tokenizer regenerate_unicode_tables -- --ignored`
//! rewrites the file; the non-ignored test fails on any drift.

use regex_syntax::ParserBuilder;
use regex_syntax::hir::{Class, HirKind};

fn ranges(class: &str) -> Vec<(u32, u32)> {
    let hir = ParserBuilder::new()
        .build()
        .parse(&format!(r"\p{{{class}}}"))
        .unwrap();
    match hir.kind() {
        HirKind::Class(Class::Unicode(c)) => c
            .ranges()
            .iter()
            .map(|r| (r.start() as u32, r.end() as u32))
            .collect(),
        _ => panic!("not a class"),
    }
}

fn render() -> String {
    let mut out = String::from(
        "//! Generated by `unicode_gen_tests::regenerate_unicode_tables`; do not edit by hand.\n\
         //! Source: regex-syntax's `\\p{L}` and `\\p{N}` classes (see that crate's\n\
         //! `unicode_tables/general_category.rs` header for the Unicode version).\n\n",
    );
    for (name, cls) in [("LETTER", "L"), ("NUMBER", "N")] {
        let r = ranges(cls);
        out.push_str(&format!(
            "/// `\\p{{{cls}}}` as sorted, disjoint, inclusive scalar-value ranges ({} ranges).\n",
            r.len()
        ));
        out.push_str(&format!(
            "#[rustfmt::skip]\npub const {name}: &[(u32, u32)] = &[\n"
        ));
        let mut line = String::from("   ");
        for (a, b) in r {
            let item = format!(" (0x{a:X}, 0x{b:X}),");
            if line.len() + item.len() > 98 {
                out.push_str(&line);
                out.push('\n');
                line = String::from("   ");
            }
            line.push_str(&item);
        }
        if !line.trim().is_empty() {
            out.push_str(&line);
            out.push('\n');
        }
        out.push_str("];\n\n");
    }
    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

const PATH: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/src/unicode_tables.rs");

#[test]
#[ignore = "writes src/unicode_tables.rs"]
fn regenerate_unicode_tables() {
    std::fs::write(PATH, render()).unwrap();
}

#[test]
fn unicode_tables_match_regex_syntax() {
    let on_disk = std::fs::read_to_string(PATH).unwrap();
    assert!(
        on_disk == render(),
        "src/unicode_tables.rs is stale; run `cargo test -p tokenizer regenerate_unicode_tables -- --ignored`"
    );
}
