import { afterAll, describe, expect, test } from "bun:test";
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import {
    databaseBinders,
    databaseUses,
    type ModuleGraph,
    OPERATION_LITERAL,
    operationLiteralHits,
    reachableModules,
} from "./module-graph";

const SRC = resolve(import.meta.dir, "..");

/** Generated by `build:tui` from `src/tui`; its modules are that tree's, not new source. */
const GENERATED = new Set([join(SRC, "tui-compiled")]);

function sourceFiles(dir: string, acc: string[] = []): string[] {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = join(dir, entry.name);
        if (GENERATED.has(full)) continue;
        if (entry.isDirectory()) sourceFiles(full, acc);
        else if (/\.(?:tsx?|mjs)$/.test(entry.name)) acc.push(full);
    }
    return acc;
}

const ALL = sourceFiles(SRC);
const TESTS = ALL.filter((file) => /\.test\.tsx?$/.test(file));
const MODULES = ALL.filter((file) => !/\.test\.tsx?$/.test(file));
/** The plugin entry is a bundle root: it reaches the runtime graph no test imports directly. */
const ENTRY = join(SRC, "index.ts");
/** The `./tui` export's source; `entry.mjs` loads its compiled copy, so the graph starts here. */
const TUI_ENTRY = join(SRC, "tui/index.tsx");
const ROOTS = [ENTRY, TUI_ENTRY, ...TESTS];

/** Not-ported subsystems; a path under any of them reachable from a bundle root is residue. The bundler names inputs relative to `SRC`, so a subsystem directly under `src` has no leading slash and the prefix must also accept the start of the path; the file alternative accepts both extensions `sourceFiles` scans. commentlint: allow(JUDGE) */
const NOT_PORTED =
    /(^|\/)(memory|dreamer|storage[^/]*|search[^/]*|embedding[^/]*|git-commits|git-anchors|user-memory)(\/|\.tsx?$)/;

/**
 * Modules no bundle root reaches through a runtime import. Type-only modules
 * are erased by the bundler and stay here; the others are waiting for the
 * unit that lands their consumer, named beside each. A module added to the
 * tree without a consumer fails this test; a consumer landing shrinks it.
 */
const AWAITING_CONSUMER = new Map<string, string>([
    ["config/load-outcome.ts", "type-only"],
    ["features/builtin-commands/types.ts", "type-only"],
    ["features/context/sidekick/index.ts", "barrel; the entry imports ./agent directly"],
    ["plugin/types.ts", "type-only"],
    ["tui/types/opencode-plugin-tui.d.ts", "type-only"],
    ["shared/context-limit-provenance.ts", "type-only"],
    ["shared/opencode-config-dir-types.ts", "type-only"],
    ["shared/format-bytes.ts", "no consumer; the TUI formats bytes with its own local helper"],
    ["shared/kernel-client-testing/state-table.ts", "tool tests (U3)"],
    ["shared/subagent-runner.ts", "sidekick (U3)"],
    ["shared/transcript.ts", "hooks (U4)"],
    [
        "testing/module-graph-report.ts",
        "test infrastructure: run as a child process, never imported",
    ],
    [
        "tui/entry.mjs",
        "the `./tui` package export: a loader whose only imports are `tui/index.tsx` (a root here) and its compiled copy, plus the host's virtual runtime registry that no bundler resolves",
    ],
]);

/**
 * The only retained module that writes a database, and the database it writes
 * is the harness's own `opencode.db`, never an Eidnara product store. Every
 * other module reaching a database binding opens it read-only.
 */
const HARNESS_DATABASE_WRITER = "features/context/compaction-marker.ts";
const HARNESS_DATABASE_READERS = ["hooks/context/read-session-db.ts"];
/** The adapter defines `Database`, so `databaseBinders` cannot include it; the test audits the adapter's constructions directly. */
const DATABASE_ADAPTER = "shared/sqlite.ts";

/** File names of the Rust-owned product stores, as a path a module could open. */
const PRODUCT_STORE_FILE =
    /^(?!\s*(?:\/\/|\*|\/\*)).*["'`/](?:memory\.sqlite|kernel\.sqlite|context\.db|store\.db)["'`]/;

type ReportedGraph = Omit<ModuleGraph, "text">;

let cachedReport: Record<string, ReportedGraph> | undefined;

/** Two tests read the report; each root is bundled once per test file run. */
function moduleGraphReport(): Record<string, ReportedGraph> {
    if (cachedReport) return cachedReport;
    const report = Bun.spawnSync({
        cmd: ["bun", join(import.meta.dir, "module-graph-report.ts"), ...ROOTS],
        cwd: SRC,
        stdout: "pipe",
        stderr: "pipe",
    });
    if (report.exitCode !== 0) {
        throw new Error(`module graph report failed: ${report.stderr.toString()}`);
    }
    cachedReport = JSON.parse(report.stdout.toString());
    return cachedReport as Record<string, ReportedGraph>;
}

describe("module graph over the landed tree", () => {
    test("the residue pattern matches a not-ported subsystem at the source root and nested under it", () => {
        expect(NOT_PORTED.test("memory/foo.ts")).toBe(true);
        expect(NOT_PORTED.test("dreamer.ts")).toBe(true);
        expect(NOT_PORTED.test("memory.tsx")).toBe(true);
        expect(NOT_PORTED.test("features/memory/foo.ts")).toBe(true);
        expect(NOT_PORTED.test("shared/user-memory.ts")).toBe(true);
        expect(NOT_PORTED.test("shared/memory-guard.ts")).toBe(false);
        expect(NOT_PORTED.test("shared/kernel-client/client.ts")).toBe(false);
    });

    test("no bundle root reaches a not-ported subsystem, and every module without a consumer is named", async () => {
        const graphs = moduleGraphReport();
        const reached = new Set<string>();
        const notPorted: string[] = [];
        for (const graph of Object.values(graphs)) {
            for (const input of graph.inputs) reached.add(resolve(SRC, input));
            for (const path of [...graph.inputs, ...graph.externals]) {
                if (NOT_PORTED.test(path)) notPorted.push(path);
            }
        }
        expect(notPorted).toEqual([]);
        const orphans = MODULES.filter((file) => !reached.has(file))
            .map((file) => relative(SRC, file))
            .sort();
        expect(orphans).toEqual([...AWAITING_CONSUMER.keys()].sort());
    }, 120_000);

    test("retained modules carry no claim.* or dreamer.* operation literal", () => {
        expect(OPERATION_LITERAL.test('"claim.intent.stage"')).toBe(true);
        expect(OPERATION_LITERAL.test("'dreamer.run_task'")).toBe(true);
        expect(OPERATION_LITERAL.test("`dreamer.run_task`")).toBe(true);
        expect(OPERATION_LITERAL.test('"dreamer_inference"')).toBe(false);
        expect(OPERATION_LITERAL.test("claim.claim_id")).toBe(false);
        expect(operationLiteralHits(MODULES)).toEqual([]);
    });

    test("retained modules name no Eidnara product-store file", () => {
        expect(PRODUCT_STORE_FILE.test('join(dir, "memory.sqlite")')).toBe(true);
        expect(PRODUCT_STORE_FILE.test("`${dir}/context.db`")).toBe(true);
        expect(PRODUCT_STORE_FILE.test("Eidnara's own context.db.")).toBe(false);
        expect(PRODUCT_STORE_FILE.test("     * applies to its own `context.db`.")).toBe(false);
        expect(operationLiteralHits(MODULES, PRODUCT_STORE_FILE)).toEqual([]);
    });

    test("the compaction marker is the only retained module that writes a database", () => {
        const binders = new Set<string>();
        for (const graph of Object.values(moduleGraphReport())) {
            for (const binder of databaseBinders(graph)) {
                if (!/\.test\.tsx?$/.test(binder)) binders.add(binder);
            }
        }
        expect([...binders].sort()).toEqual(
            [HARNESS_DATABASE_WRITER, ...HARNESS_DATABASE_READERS].sort(),
        );
        const opens = (module: string) => {
            const uses = databaseUses(readFileSync(join(SRC, module), "utf8"), module);
            expect(uses.escapes).toEqual([]);
            return uses.opens;
        };
        for (const reader of HARNESS_DATABASE_READERS) {
            expect(opens(reader)).toEqual([
                "    const db = new Database(dbPath, { readonly: true });",
            ]);
        }
        expect(opens(HARNESS_DATABASE_WRITER)).toEqual(["    const db = new Database(dbPath);"]);
        expect(readFileSync(join(SRC, HARNESS_DATABASE_WRITER), "utf8")).toMatch(
            /const dbPath = getOpenCodeDbPath\(\);/,
        );
        expect(
            databaseUses(readFileSync(join(SRC, DATABASE_ADAPTER), "utf8"), DATABASE_ADAPTER, {
                allConstructions: true,
            }),
        ).toEqual({
            opens: [
                "        throw new TypeError(",
                "            throw new TypeError(",
                "        throw new Error(`unable to open database file: ${location} does not exist`);",
                "            throw new SqliteRuntimeUnavailableError(runtime, specifier, error);",
                "const privilegeDepth = new WeakMap<Database, number>();",
                "        throw new TypeError(",
                "        throw new TypeError(",
                '    const probe = new Database(":memory:");',
            ],
            escapes: [
                "const DatabaseImpl: typeof BetterSqlite3 = isBun",
                "    ? buildBunSqliteDatabaseClass(sqliteModule.Database)",
                "    : buildNodeSqliteDatabaseClass(sqliteModule.DatabaseSync);",
                "export function buildBunSqliteDatabaseClass(BunDatabase: any): typeof BetterSqlite3 {",
                "    class BunSqliteDatabase extends BunDatabase {",
                "    return BunSqliteDatabase as unknown as typeof BetterSqlite3;",
                "export function buildNodeSqliteDatabaseClass(DatabaseSync: any): typeof BetterSqlite3 {",
                "    class NodeSqliteDatabase extends DatabaseSync {",
                "    return NodeSqliteDatabase as unknown as typeof BetterSqlite3;",
                "export const Database: typeof BetterSqlite3 = DatabaseImpl;",
            ],
        });
    }, 120_000);
});
const graph: ModuleGraph = {
    inputs: ["src/a/forbidden.ts", "src/b/forbidden.ts", "src/c/allowed.ts"],
    externals: ["@scope/forbidden-external", "@scope/allowed-external"],
    imports: {
        "src/a/forbidden.ts": ["bun:sqlite"],
        "src/b/forbidden.ts": ["../shared/sqlite"],
        "src/c/allowed.ts": ["src/a/forbidden.ts", "@scope/allowed-external"],
        "src/shared/sqlite.ts": ["node:sqlite"],
    },
    text: "",
};

describe("reachableModules", () => {
    test("returns every input and external matching the pattern", () => {
        expect(reachableModules(graph, /forbidden/)).toEqual([
            "src/a/forbidden.ts",
            "src/b/forbidden.ts",
            "@scope/forbidden-external",
        ]);
    });

    test("returns an empty list when nothing matches", () => {
        expect(reachableModules(graph, /never-present/)).toEqual([]);
    });

    // `RegExp.prototype.test` advances `lastIndex` on `g` and `y` patterns, so a
    // silent under-count would make a reachable module look unreachable.
    test("rejects a global pattern instead of under-counting", () => {
        expect(() => reachableModules(graph, /forbidden/g)).toThrow(TypeError);
    });

    test("rejects a sticky pattern instead of under-counting", () => {
        expect(() => reachableModules(graph, /forbidden/y)).toThrow(TypeError);
    });
});

describe("databaseBinders", () => {
    test("names every module importing a binding, including an adapter that imports one statically", () => {
        expect(databaseBinders(graph)).toEqual([
            "src/a/forbidden.ts",
            "src/b/forbidden.ts",
            "src/shared/sqlite.ts",
        ]);
    });
});

describe("databaseUses", () => {
    const allowed = [
        'import { Database, runImmediate } from "../../shared/sqlite";',
        'import type BetterSqlite3 from "better-sqlite3";',
        "let cached: { path: string; db: Database } | null = null;",
        "function open(dbPath: string): Database {",
        "    const db = new Database(dbPath, { readonly: true });",
        "    return db;",
        "}",
        "type Ctor = typeof Database;",
        "type Database = BetterSqlite3.Database;",
        "const meta = { Database: 1 };",
        "const name = meta.Database;",
        "",
    ].join("\n");

    test("reports each open by its source line and no escape for imports, types, and member names", () => {
        expect(databaseUses(allowed)).toEqual({
            opens: ["    const db = new Database(dbPath, { readonly: true });"],
            escapes: [],
        });
    });

    test("reports a local alias of the constructor as an escape, and the aliased open as an open", () => {
        const uses = databaseUses(
            [
                'import { Database } from "../../shared/sqlite";',
                "const DB = Database;",
                "const db = new DB(productPath);",
                "const other = new Database(dbPath);",
                "",
            ].join("\n"),
        );
        expect(uses.escapes).toEqual(["const DB = Database;"]);
        expect(uses.opens).toEqual(["const other = new Database(dbPath);"]);
    });

    test("reports a constructor passed as a value, extended, or re-exported as an escape", () => {
        const uses = databaseUses(
            [
                'import { Database } from "../../shared/sqlite";',
                "const db = Reflect.construct(Database, [productPath]);",
                "class Store extends Database {}",
                "const { Database: D } = { Database };",
                "export { Database };",
                "",
            ].join("\n"),
        );
        expect(uses.escapes).toEqual([
            "const db = Reflect.construct(Database, [productPath]);",
            "class Store extends Database {}",
            "const { Database: D } = { Database };",
            "export { Database };",
        ]);
    });

    test("reports aliased, namespace, default, re-exported, and dynamic binding imports as escapes", () => {
        const uses = databaseUses(
            [
                'import { Database as DB } from "../../shared/sqlite";',
                'import * as sqlite from "../../shared/sqlite";',
                'import bun from "bun:sqlite";',
                'export * from "../../shared/sqlite";',
                'export { default as Db } from "better-sqlite3";',
                'const lazy = await import("node:sqlite");',
                'const legacy = require("better-sqlite3");',
                'import { join } from "node:path";',
                "",
            ].join("\n"),
        );
        expect(uses.escapes).toEqual([
            'import { Database as DB } from "../../shared/sqlite";',
            'import * as sqlite from "../../shared/sqlite";',
            'import bun from "bun:sqlite";',
            'export * from "../../shared/sqlite";',
            'export { default as Db } from "better-sqlite3";',
            'const lazy = await import("node:sqlite");',
            'const legacy = require("better-sqlite3");',
        ]);
    });

    test("reports any constructor named like the binding as an open", () => {
        expect(databaseUses("const probe = new DatabaseSync(':memory:');").opens).toEqual([
            "const probe = new DatabaseSync(':memory:');",
        ]);
    });

    test("under allConstructions, an alias of an implementation constructor is both an escape and an open", () => {
        const uses = databaseUses(
            [
                "const DatabaseImpl = buildNodeSqliteDatabaseClass(mod.DatabaseSync);",
                "const DB = DatabaseImpl;",
                "const leak = new DB(productPath);",
                "const marker = new Error('x');",
                "",
            ].join("\n"),
            "module.ts",
            { allConstructions: true },
        );
        expect(uses.escapes).toEqual([
            "const DatabaseImpl = buildNodeSqliteDatabaseClass(mod.DatabaseSync);",
            "const DB = DatabaseImpl;",
        ]);
        expect(uses.opens).toEqual([
            "const leak = new DB(productPath);",
            "const marker = new Error('x');",
        ]);
    });
});

describe("operationLiteralHits", () => {
    const dir = mkdtempSync(join(tmpdir(), "eidnara-literal-hits-"));
    const file = join(dir, "probe.ts");
    writeFileSync(
        file,
        ['const a = "claim.intent.stage";', 'const b = "claim.intent.ack";', ""].join("\n"),
    );
    afterAll(() => rmSync(dir, { recursive: true, force: true }));

    test("reports every matching line with its one-based number", () => {
        expect(operationLiteralHits([file])).toEqual([`${file}:1`, `${file}:2`]);
    });

    // `RegExp.prototype.test` advances `lastIndex` for global and sticky patterns;
    // a stale offset skips a real literal on the next line and the scan passes vacuously.
    test("rejects a global pattern instead of under-counting", () => {
        expect(() => operationLiteralHits([file], /claim\./g)).toThrow(TypeError);
    });

    test("rejects a sticky pattern instead of under-counting", () => {
        expect(() => operationLiteralHits([file], /claim\./y)).toThrow(TypeError);
    });
});
