import { afterAll, describe, expect, test } from "bun:test";
import { mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import {
    CODE_FILE,
    DATABASE_BINDING,
    type DatabaseUses,
    databaseBinders,
    databaseUses,
    firstPartyInputs,
    literalStrings,
    type ModuleGraph,
    OPERATION_LITERAL,
    operationLiteralHits,
    PRODUCT_STORE_FILE,
    parseSource,
    RETAINED_DATABASE_USES,
    reachableModules,
    resolvesToBinding,
    TEST_FILE,
    withoutComments,
} from "./module-graph";

const SRC = resolve(import.meta.dir, "..");

/** Generated by `build:tui` from `src/tui`; its modules are that tree's, not new source. */
const GENERATED = new Set([join(SRC, "tui-compiled")]);

function sourceFiles(dir: string, acc: string[] = [], skipGenerated = true): string[] {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const full = join(dir, entry.name);
        if (skipGenerated && GENERATED.has(full)) continue;
        if (entry.isDirectory()) sourceFiles(full, acc, skipGenerated);
        else if (CODE_FILE.test(entry.name)) acc.push(full);
    }
    return acc;
}

const ALL = sourceFiles(SRC);
const TESTS = ALL.filter((file) => TEST_FILE.test(file));
const MODULES = ALL.filter((file) => !TEST_FILE.test(file));
/** The plugin entry is a bundle root: it reaches the runtime graph no test imports directly. */
const ENTRY = join(SRC, "index.ts");
/** The `./tui` export's source; `entry.mjs` loads its compiled copy, so the graph starts here. */
const TUI_ENTRY = join(SRC, "tui/index.tsx");
const ROOTS = [ENTRY, TUI_ENTRY, ...TESTS];

/** Not-ported subsystems; a path under any of them reachable from a bundle root is residue. The bundler names inputs relative to `SRC`, so a subsystem directly under `src` has no leading slash and the prefix must also accept the start of the path; the file alternative accepts every extension `sourceFiles` scans. commentlint: allow(JUDGE) */
const NOT_PORTED =
    /(^|\/)(memory|dreamer|storage[^/]*|search[^/]*|embedding[^/]*|git-commits|git-anchors|user-memory)(\/|\.(?:[cm]?[jt]s|[jt]sx)$)/;

/**
 * Modules no bundle root reaches through a runtime import. Type-only modules
 * are erased by the bundler and stay here; the others are waiting for the
 * unit that lands their consumer, named beside each. A module added to the
 * tree without a consumer fails this test; a consumer landing shrinks it.
 */
const AWAITING_CONSUMER = new Map<string, string>([
    ["config/load-outcome.ts", "type-only"],
    ["features/builtin-commands/types.ts", "type-only"],
    ["features/context/sidekick/index.ts", "barrel; the entry imports ./agent directly"],
    ["plugin/types.ts", "type-only"],
    ["tui/types/opencode-plugin-tui.d.ts", "type-only"],
    ["shared/context-limit-provenance.ts", "type-only"],
    ["shared/opencode-config-dir-types.ts", "type-only"],
    ["shared/format-bytes.ts", "no consumer; the TUI formats bytes with its own local helper"],
    ["shared/kernel-client-testing/state-table.ts", "tool tests (U3)"],
    ["shared/subagent-runner.ts", "sidekick (U3)"],
    ["shared/transcript.ts", "hooks (U4)"],
    [
        "testing/module-graph-report.ts",
        "test infrastructure: run as a child process, never imported",
    ],
    [
        "tui/entry.mjs",
        "the `./tui` package export: a loader whose only imports are `tui/index.tsx` (a root here) and its compiled copy, plus the host's virtual runtime registry that no bundler resolves",
    ],
]);

/**
 * The only retained module that writes a database, and the database it writes
 * is the harness's own `opencode.db`, never an Eidnara product store. Every
 * other module reaching a database binding opens it read-only.
 */
const HARNESS_DATABASE_WRITER = "features/context/compaction-marker.ts";
const HARNESS_DATABASE_READERS = ["hooks/context/read-session-db.ts"];
/** The adapter defines `Database`, so `databaseBinders` cannot include it; the test audits the adapter's constructions directly. */
const DATABASE_ADAPTER = "shared/sqlite.ts";

type ReportedGraph = Omit<ModuleGraph, "text">;

let cachedReport: Record<string, ReportedGraph> | undefined;

/** Two tests read the report; each root is bundled once per test file run. */
function moduleGraphReport(): Record<string, ReportedGraph> {
    if (cachedReport) return cachedReport;
    const report = Bun.spawnSync({
        cmd: ["bun", join(import.meta.dir, "module-graph-report.ts"), ...ROOTS],
        cwd: SRC,
        stdout: "pipe",
        stderr: "pipe",
    });
    if (report.exitCode !== 0) {
        throw new Error(`module graph report failed: ${report.stderr.toString()}`);
    }
    cachedReport = JSON.parse(report.stdout.toString());
    return cachedReport as Record<string, ReportedGraph>;
}

const PRODUCTION_ROOTS = [ENTRY, TUI_ENTRY];

/**
 * Every first-party file a production root bundles, wherever it lives: the retained tree, a
 * sibling workspace package, a JSON data file, but not a third-party dependency. A production
 * root must never reach a test-named file, since the state-ownership scans select by file name.
 */
function productionReached(): string[] {
    const graphs = moduleGraphReport();
    const reached = new Set<string>();
    for (const root of PRODUCTION_ROOTS) {
        const graph = graphs[root];
        if (!graph) throw new Error(`no graph for production root ${root}`);
        const inputs = firstPartyInputs(graph);
        for (const input of [...inputs.code, ...inputs.data]) reached.add(resolve(SRC, input));
    }
    const testNamed = [...reached].filter((file) => TEST_FILE.test(file));
    expect(testNamed).toEqual([]);
    return [...reached].sort();
}

/**
 * The retained tree, whatever production reaches outside it, and the generated compiled TUI
 * that the `./tui` export loads at runtime; the compiled tree is not a module source for the
 * orphan check, but its bytes ship, so the literal and database scans read them.
 */
function scannedSources(): string[] {
    const compiled = [...GENERATED].flatMap((dir) => sourceFiles(dir, [], false));
    return [...new Set([...MODULES, ...productionReached(), ...compiled])].sort();
}

/** `literalScanSources` excludes `SCAN_DEFINITIONS` because `OPERATION_LITERAL` expands to `"claim.` in that file; `productionReached` must never name it. */
const SCAN_DEFINITIONS = join(SRC, "testing/module-graph.ts");

function literalScanSources(): string[] {
    expect(productionReached()).not.toContain(SCAN_DEFINITIONS);
    return scannedSources().filter((file) => file !== SCAN_DEFINITIONS);
}

describe("module graph over the landed tree", () => {
    test("the residue pattern matches a not-ported subsystem at the source root and nested under it", () => {
        expect(NOT_PORTED.test("memory/foo.ts")).toBe(true);
        expect(NOT_PORTED.test("dreamer.ts")).toBe(true);
        expect(NOT_PORTED.test("memory.tsx")).toBe(true);
        expect(NOT_PORTED.test("memory.mjs")).toBe(true);
        expect(NOT_PORTED.test("tui/dreamer.mjs")).toBe(true);
        expect(NOT_PORTED.test("shared/user-memory.cjs")).toBe(true);
        expect(NOT_PORTED.test("features/memory/panel.jsx")).toBe(true);
        expect(NOT_PORTED.test("features/memory/foo.ts")).toBe(true);
        expect(NOT_PORTED.test("shared/user-memory.ts")).toBe(true);
        expect(NOT_PORTED.test("shared/memory-guard.ts")).toBe(false);
        expect(NOT_PORTED.test("shared/kernel-client/client.ts")).toBe(false);
    });

    test("no bundle root reaches a not-ported subsystem, and every module without a consumer is named", async () => {
        const graphs = moduleGraphReport();
        const reached = new Set<string>();
        const notPorted: string[] = [];
        for (const graph of Object.values(graphs)) {
            for (const input of graph.inputs) reached.add(resolve(SRC, input));
            for (const path of [...graph.inputs, ...graph.externals]) {
                if (NOT_PORTED.test(path)) notPorted.push(path);
            }
        }
        expect(notPorted).toEqual([]);
        const orphans = MODULES.filter((file) => !reached.has(file))
            .map((file) => relative(SRC, file))
            .sort();
        expect(orphans).toEqual([...AWAITING_CONSUMER.keys()].sort());
    }, 120_000);

    test("retained modules carry no claim.* or dreamer.* operation literal", () => {
        expect(OPERATION_LITERAL.test('"claim.intent.stage"')).toBe(true);
        expect(OPERATION_LITERAL.test("'dreamer.run_task'")).toBe(true);
        expect(OPERATION_LITERAL.test("`dreamer.run_task`")).toBe(true);
        expect(OPERATION_LITERAL.test('"claim.intent-stage"')).toBe(true);
        expect(OPERATION_LITERAL.test("`dreamer.${task}`")).toBe(true);
        expect(OPERATION_LITERAL.test('"CLAIM.INTENT.STAGE"')).toBe(true);
        expect(OPERATION_LITERAL.test("'Dreamer.Run_Task'")).toBe(true);
        expect(OPERATION_LITERAL.test('"dreamer_inference"')).toBe(false);
        expect(OPERATION_LITERAL.test("claim.claim_id")).toBe(false);
        expect(operationLiteralHits(literalScanSources())).toEqual([]);
    }, 120_000);

    test("retained modules name no Eidnara product-store file", () => {
        expect(PRODUCT_STORE_FILE.test('join(dir, "memory.sqlite")')).toBe(true);
        expect(PRODUCT_STORE_FILE.test("`${dir}/context.db`")).toBe(true);
        expect(PRODUCT_STORE_FILE.test('"context.db?mode=ro"')).toBe(true);
        expect(PRODUCT_STORE_FILE.test("'store.db-wal'")).toBe(true);
        expect(PRODUCT_STORE_FILE.test("`memory.sqlite.bak`")).toBe(true);
        expect(PRODUCT_STORE_FILE.test('"context.dbx"')).toBe(false);
        expect(PRODUCT_STORE_FILE.test("Eidnara's own context.db.")).toBe(false);
        expect(operationLiteralHits(literalScanSources(), PRODUCT_STORE_FILE)).toEqual([]);
    }, 120_000);

    test("the compaction marker is the only retained module that writes a database", () => {
        const binders = new Set<string>();
        for (const [root, graph] of Object.entries(moduleGraphReport())) {
            const testRoot = TESTS.includes(root);
            for (const binder of databaseBinders(graph)) {
                // A test root may bind a database itself; every module it reaches, and every
                // module a production root reaches, is audited whatever its file name.
                if (testRoot && resolve(SRC, binder) === root) continue;
                binders.add(binder);
            }
        }
        expect([...binders].sort()).toEqual(
            [HARNESS_DATABASE_WRITER, ...HARNESS_DATABASE_READERS].sort(),
        );
        for (const reader of HARNESS_DATABASE_READERS) {
            expect(RETAINED_DATABASE_USES[reader]?.opens).toEqual([
                "    const db = new Database(dbPath, { readonly: true });",
            ]);
        }
        expect(readFileSync(join(SRC, HARNESS_DATABASE_WRITER), "utf8")).toMatch(
            /const dbPath = getOpenCodeDbPath\(\);/,
        );
        // Every retained module is read directly, so an open, an alias, or a computed load in a
        // module no graph edge names as a binder still lands here.
        const uses: Record<string, DatabaseUses> = {};
        for (const file of scannedSources()) {
            const module = relative(SRC, file);
            const found = databaseUses(readFileSync(file, "utf8"), module);
            if (found.opens.length > 0 || found.escapes.length > 0) uses[module] = found;
        }
        expect(uses).toEqual(RETAINED_DATABASE_USES);
        expect(
            databaseUses(readFileSync(join(SRC, DATABASE_ADAPTER), "utf8"), DATABASE_ADAPTER, {
                allConstructions: true,
            }),
        ).toEqual({
            opens: [
                "        throw new TypeError(",
                "            throw new TypeError(",
                "        throw new Error(`unable to open database file: ${location} does not exist`);",
                "            throw new SqliteRuntimeUnavailableError(runtime, specifier, error);",
                "const privilegeDepth = new WeakMap<Database, number>();",
                "        throw new TypeError(",
                "        throw new TypeError(",
                '    const probe = new Database(":memory:");',
            ],
            escapes: RETAINED_DATABASE_USES[DATABASE_ADAPTER]?.escapes,
        });
    }, 120_000);
});
const graph: ModuleGraph = {
    inputs: ["src/a/forbidden.ts", "src/b/forbidden.ts", "src/c/allowed.ts"],
    externals: ["@scope/forbidden-external", "@scope/allowed-external"],
    imports: {
        "src/a/forbidden.ts": ["bun:sqlite"],
        "src/b/forbidden.ts": ["../shared/sqlite"],
        "src/c/allowed.ts": ["src/a/forbidden.ts", "@scope/allowed-external"],
        "src/shared/sqlite.ts": ["node:sqlite"],
    },
    text: "",
};

describe("reachableModules", () => {
    test("returns every input and external matching the pattern", () => {
        expect(reachableModules(graph, /forbidden/)).toEqual([
            "src/a/forbidden.ts",
            "src/b/forbidden.ts",
            "@scope/forbidden-external",
        ]);
    });

    test("returns an empty list when nothing matches", () => {
        expect(reachableModules(graph, /never-present/)).toEqual([]);
    });

    // `RegExp.prototype.test` advances `lastIndex` on `g` and `y` patterns, so a
    // silent under-count would make a reachable module look unreachable.
    test("rejects a global pattern instead of under-counting", () => {
        expect(() => reachableModules(graph, /forbidden/g)).toThrow(TypeError);
    });

    test("rejects a sticky pattern instead of under-counting", () => {
        expect(() => reachableModules(graph, /forbidden/y)).toThrow(TypeError);
    });
});

describe("databaseBinders", () => {
    test("names every module importing a binding, including an adapter that imports one statically", () => {
        expect(databaseBinders(graph)).toEqual([
            "src/a/forbidden.ts",
            "src/b/forbidden.ts",
            "src/shared/sqlite.ts",
        ]);
    });

    test("matches the adapter under any executable extension", () => {
        for (const spelling of [
            "../../shared/sqlite",
            "../../shared/sqlite.ts",
            "../../shared/sqlite.js",
            "../../shared/sqlite.mjs",
            "../../shared/sqlite.cts",
        ]) {
            expect(DATABASE_BINDING.test(spelling)).toBe(true);
        }
        expect(DATABASE_BINDING.test("../../shared/sqlite.json")).toBe(false);
        expect(DATABASE_BINDING.test("../../shared/sqlite-helpers")).toBe(false);
    });

    test("resolves a relative specifier against the importing module before matching", () => {
        expect(resolvesToBinding("src/shared/beside.ts", "./sqlite")).toBe(true);
        expect(resolvesToBinding("src/shared/nested/deep.ts", "../sqlite.ts")).toBe(true);
        expect(resolvesToBinding("src/hooks/x.ts", "./sqlite")).toBe(false);
        expect(resolvesToBinding("src/shared/beside.ts", "./sqlite-helpers")).toBe(false);
        expect(resolvesToBinding("src/shared/beside.ts", "node:sqlite")).toBe(true);
        expect(
            databaseBinders({
                imports: {
                    "src/shared/beside.ts": ["./sqlite"],
                    "src/shared/other.ts": ["./sqlite-helpers"],
                },
            }),
        ).toEqual(["src/shared/beside.ts"]);
    });
});

describe("databaseUses", () => {
    const allowed = [
        'import { Database, runImmediate } from "../../shared/sqlite";',
        'import { type Database as Db } from "../../shared/sqlite";',
        'import type BetterSqlite3 from "better-sqlite3";',
        "let cached: { path: string; db: Db } | null = null;",
        "function open(dbPath: string): Database {",
        "    const db = new Database(dbPath, { readonly: true });",
        "    return db;",
        "}",
        "type Ctor = typeof Database;",
        "type Database = BetterSqlite3.Database;",
        "const meta = { Database: 1 };",
        "const name = meta.Database;",
        "",
    ].join("\n");

    test("reports each open by its source line and no escape for imports, inline type aliases, types, and member names", () => {
        expect(databaseUses(allowed)).toEqual({
            opens: ["    const db = new Database(dbPath, { readonly: true });"],
            escapes: [],
        });
    });

    test("reports a local alias of the constructor as an escape, and the aliased open as an open", () => {
        const uses = databaseUses(
            [
                'import { Database } from "../../shared/sqlite";',
                "const DB = Database;",
                "const db = new DB(productPath);",
                "const other = new Database(dbPath);",
                "",
            ].join("\n"),
        );
        expect(uses.escapes).toEqual(["const DB = Database;"]);
        expect(uses.opens).toEqual(["const other = new Database(dbPath);"]);
    });

    test("reports a constructor passed as a value, extended, or re-exported as an escape", () => {
        const uses = databaseUses(
            [
                'import { Database } from "../../shared/sqlite";',
                "const db = Reflect.construct(Database, [productPath]);",
                "class Store extends Database {}",
                "const { Database: D } = { Database };",
                "export { Database };",
                "",
            ].join("\n"),
        );
        expect(uses.escapes).toEqual([
            "const db = Reflect.construct(Database, [productPath]);",
            "class Store extends Database {}",
            "const { Database: D } = { Database };",
            "export { Database };",
        ]);
    });

    test("reports a computed constructor as an escape and a plain one only as an open", () => {
        const uses = databaseUses(
            [
                'import { Database } from "../../shared/sqlite";',
                "const db = new Database(dbPath, { readonly: true });",
                "const copy = new db.constructor(productPath);",
                'const picked = new sqlite["Database"](productPath);',
                "const made = new (pick())(productPath);",
                "const plain = new Map<string, number>();",
                "const built = Reflect.construct(sqliteModule.DatabaseSync, [dynamicPath]);",
                "",
            ].join("\n"),
        );
        expect(uses.opens).toEqual([
            "const db = new Database(dbPath, { readonly: true });",
            'const picked = new sqlite["Database"](productPath);',
        ]);
        expect(uses.escapes).toEqual([
            "const copy = new db.constructor(productPath);",
            'const picked = new sqlite["Database"](productPath);',
            "const made = new (pick())(productPath);",
            "const built = Reflect.construct(sqliteModule.DatabaseSync, [dynamicPath]);",
        ]);
        expect(
            databaseUses(
                [
                    'import type { Database } from "bun:sqlite";',
                    'export type { Database as Db } from "../../shared/sqlite";',
                    'import type Native = require("node:sqlite");',
                    'const names = new Intl.DisplayNames(["en"], { type: "language" });',
                    "const again = new handle.constructor(productPath);",
                    "const Ctor = handle.constructor;",
                    "const { constructor: Picked } = handle;",
                    "let Late;",
                    'Late = handle["constructor"];',
                    "const Chained = Ctor;",
                    "const viaCtor = new Ctor(productPath);",
                    "const viaPicked = new Picked(productPath);",
                    "const viaLate = new Late(productPath);",
                    "const viaChained = new Chained(productPath);",
                    "const plain = new Map();",
                    "const reflected = Reflect.construct(handle.constructor, [productPath]);",
                    "const other = Reflect.construct(Map, []);",
                    "",
                ].join("\n"),
            ).escapes,
        ).toEqual([
            "const again = new handle.constructor(productPath);",
            "const viaCtor = new Ctor(productPath);",
            "const viaPicked = new Picked(productPath);",
            "const viaLate = new Late(productPath);",
            "const viaChained = new Chained(productPath);",
            "const reflected = Reflect.construct(handle.constructor, [productPath]);",
        ]);
    });

    test("reports aliased, namespace, default, re-exported, and dynamic binding imports as escapes", () => {
        const uses = databaseUses(
            [
                'import { Database as DB } from "../../shared/sqlite";',
                'import * as sqlite from "../../shared/sqlite";',
                'import bun from "bun:sqlite";',
                'export * from "../../shared/sqlite";',
                'export * as sqliteNs from "../../shared/sqlite";',
                'export { default as Db } from "better-sqlite3";',
                'export { type Database, runImmediate } from "../../shared/sqlite";',
                'const lazy = await import("node:sqlite");',
                'const legacy = require("better-sqlite3");',
                'import { join } from "node:path";',
                'export type { Database } from "../../shared/sqlite";',
                'export { type Database as TypeOnlyDb } from "../../shared/sqlite";',
                'import native = require("node:sqlite");',
                'import type NativeTypes = require("node:sqlite");',
                'import pathModule = require("node:path");',
                "",
            ].join("\n"),
        );
        expect(uses.escapes).toEqual([
            'import { Database as DB } from "../../shared/sqlite";',
            'import * as sqlite from "../../shared/sqlite";',
            'import bun from "bun:sqlite";',
            'export * from "../../shared/sqlite";',
            'export * as sqliteNs from "../../shared/sqlite";',
            'export { default as Db } from "better-sqlite3";',
            'export { type Database, runImmediate } from "../../shared/sqlite";',
            'const lazy = await import("node:sqlite");',
            'const legacy = require("better-sqlite3");',
            'import native = require("node:sqlite");',
        ]);
    });

    test("recognizes the adapter imported by a sibling-relative specifier", () => {
        const uses = databaseUses(
            [
                'import { Database as Sqlite } from "./sqlite";',
                "const db = new Sqlite(dynamicPath);",
                "",
            ].join("\n"),
            "shared/beside.ts",
        );
        expect(uses.escapes).toEqual(['import { Database as Sqlite } from "./sqlite";']);
        expect(
            databaseUses('import { Database as Sqlite } from "./sqlite";\n', "hooks/far.ts")
                .escapes,
        ).toEqual([]);
    });

    test("reports any constructor named like the binding as an open", () => {
        expect(databaseUses("const probe = new DatabaseSync(':memory:');").opens).toEqual([
            "const probe = new DatabaseSync(':memory:');",
        ]);
    });

    test("reports no escape for ambient declarations, which emit no value", () => {
        expect(
            databaseUses(
                [
                    'declare module "sqlite-shim" {',
                    "    class Database {}",
                    "    const DatabaseSync: typeof Database;",
                    "    export { Database, DatabaseSync };",
                    "}",
                    "",
                ].join("\n"),
                "shim.d.ts",
            ),
        ).toEqual({ opens: [], escapes: [] });
        expect(
            databaseUses(
                [
                    "declare class Database {}",
                    "declare const DatabaseImpl: typeof Database;",
                    "const DB = Database;",
                    "",
                ].join("\n"),
            ).escapes,
        ).toEqual(["const DB = Database;"]);
    });

    test("reports a binding loaded through a createRequire-bound function as an escape", () => {
        expect(
            databaseUses(
                [
                    'import { createRequire } from "node:module";',
                    "const load = createRequire(import.meta.url);",
                    'const { DatabaseSync: Sqlite } = load("node:sqlite");',
                    'const other = load("node:path");',
                    'const viaModule = module.require("better-sqlite3");',
                    'import { createRequire as makeRequire } from "node:module";',
                    "const aliased = makeRequire(import.meta.url);",
                    'const bun = aliased("bun:sqlite");',
                    'const { DatabaseSync: Builtin } = process.getBuiltinModule("node:sqlite");',
                    'const path = process.getBuiltinModule("node:path");',
                    "const make = createRequire;",
                    "const local = make(import.meta.url);",
                    'const better = local("better-sqlite3");',
                    'import * as mod from "node:module";',
                    "const { createRequire: picked } = mod;",
                    "const viaPick = picked(import.meta.url);",
                    'const nodeSql = viaPick("node:sqlite");',
                    'const { ["createRequire"]: computed } = mod;',
                    "const viaComputed = computed(import.meta.url);",
                    'const bunSql = viaComputed("bun:sqlite");',
                    "const run = load;",
                    'const ran = run("bun:sqlite");',
                    "const { require: unrelated } = someObject;",
                    'const notALoad = unrelated("bun:sqlite");',
                    "const builtin = process.getBuiltinModule;",
                    'const viaBuiltinAlias = builtin("node:sqlite");',
                    "let late;",
                    "late = createRequire(import.meta.url);",
                    'const lateLoad = late("node:sqlite");',
                    'const { DatabaseSync: Elem } = process["getBuiltinModule"]("node:sqlite");',
                    "",
                ].join("\n"),
            ).escapes,
        ).toEqual([
            'const { DatabaseSync: Sqlite } = load("node:sqlite");',
            'const viaModule = module.require("better-sqlite3");',
            'const bun = aliased("bun:sqlite");',
            'const { DatabaseSync: Builtin } = process.getBuiltinModule("node:sqlite");',
            'const better = local("better-sqlite3");',
            'const nodeSql = viaPick("node:sqlite");',
            'const bunSql = viaComputed("bun:sqlite");',
            'const ran = run("bun:sqlite");',
            'const viaBuiltinAlias = builtin("node:sqlite");',
            'const lateLoad = late("node:sqlite");',
            'const { DatabaseSync: Elem } = process["getBuiltinModule"]("node:sqlite");',
        ]);
    });

    test("reports a dynamic load with a computed specifier as an escape", () => {
        expect(
            databaseUses(
                [
                    'const spec = "node:" + "sqlite";',
                    "const mod = await import(spec);",
                    "const legacy = require(process.env.DB_MODULE);",
                    'const known = await import("node:path");',
                    "",
                ].join("\n"),
            ).escapes,
        ).toEqual([
            "const mod = await import(spec);",
            "const legacy = require(process.env.DB_MODULE);",
        ]);
    });

    test("reports no escape for declaration names and type-only positions", () => {
        expect(
            databaseUses(
                [
                    'import { Database } from "../../shared/sqlite";',
                    "interface DatabaseRow {",
                    "    id: number;",
                    "}",
                    "function pick<DatabaseLike>(row: DatabaseLike): DatabaseLike {",
                    "    return row;",
                    "}",
                    "class Facade implements Database {}",
                    'type Native = import("better-sqlite3").Database;',
                    "function isStore(value: unknown): value is Database {",
                    "    return value instanceof Database;",
                    "}",
                    "",
                ].join("\n"),
            ),
        ).toEqual({
            opens: [],
            escapes: ["    return value instanceof Database;"],
        });
    });

    test("under allConstructions, an alias of an implementation constructor is both an escape and an open", () => {
        const uses = databaseUses(
            [
                "const DatabaseImpl = buildNodeSqliteDatabaseClass(mod.DatabaseSync);",
                "const DB = DatabaseImpl;",
                "const leak = new DB(productPath);",
                "const marker = new Error('x');",
                "",
            ].join("\n"),
            "module.ts",
            { allConstructions: true },
        );
        expect(uses.escapes).toEqual([
            "const DatabaseImpl = buildNodeSqliteDatabaseClass(mod.DatabaseSync);",
            "const DB = DatabaseImpl;",
        ]);
        expect(uses.opens).toEqual([
            "const leak = new DB(productPath);",
            "const marker = new Error('x');",
        ]);
    });
});

describe("parseSource", () => {
    test("rejects a file whose recovered tree could omit an audited construction", () => {
        const malformed = ["const t = `oops;", "const db = new Database(productPath);", ""].join(
            "\n",
        );
        expect(() => parseSource(malformed, "m.ts")).toThrow(/TS1160\b/);
        expect(() => databaseUses(malformed)).toThrow(SyntaxError);
        expect(() => parseSource("const a: number = 1;", "m.mjs")).toThrow(/TS8010\b/);
        expect(() => parseSource("export const X = <div>{1}</div>;", "m.tsx")).not.toThrow();
    });
});

describe("operationLiteralHits", () => {
    const dir = mkdtempSync(join(tmpdir(), "eidnara-literal-hits-"));
    const file = join(dir, "probe.ts");
    writeFileSync(
        file,
        ['const a = "claim.intent.stage";', 'const b = "claim.intent.ack";', ""].join("\n"),
    );
    const commented = join(dir, "commented.tsx");
    writeFileSync(
        commented,
        [
            "/**",
            " * applies to its own `context.db`.",
            " */",
            'const a = 1; // trailing "context.db"',
            '/* compatibility */ writeFileSync(join(dir, "context.db"), data);',
            "const b = `not // a comment ${x}/store.db`;",
            "export const X = <div>text {`${y}/kernel.sqlite`}</div>;",
            'const assembled = "memory" + ".sq" + "lite";',
            'const partial = "memory" + suffix;',
            'const later = join(dir, "store.db");',
            'const escaped = join(dir, "context\\u002edb");',
            'const templated = join(dir, `${"context"}.db`);',
            "const matcher = /^memory\\.sqlite$/.test(name);",
            "",
        ].join("\n"),
    );
    afterAll(() => rmSync(dir, { recursive: true, force: true }));

    test("reports every matching line with its one-based number", () => {
        expect(operationLiteralHits([file])).toEqual([`${file}:1`, `${file}:2`]);
    });

    test("blanks comments but keeps code after a closed block comment, template text, JSX, and folded concatenations", () => {
        expect(operationLiteralHits([commented], PRODUCT_STORE_FILE)).toEqual([
            `${commented}:5`,
            `${commented}:6`,
            `${commented}:7`,
            `${commented}:8`,
            `${commented}:10`,
            `${commented}:11`,
            `${commented}:12`,
            `${commented}:13`,
        ]);
        expect(withoutComments("/* a */ b // c\n", "m.ts")).toBe("        b     \n");
        expect(
            literalStrings(parseSource('const op = ("claim." + "intent") + ".stage";', "m.ts")).map(
                (entry) => entry.value,
            ),
        ).toEqual(["claim.intent.stage", "claim.intent", "claim.", "intent", ".stage"]);
        expect(
            literalStrings(
                parseSource('const f = "context\\u002edb"; const t = `x${y}/store.db`;', "m.ts"),
            ).map((entry) => entry.value),
        ).toEqual(["context.db", "x", "/store.db"]);
        expect(
            literalStrings(
                parseSource(
                    'const t = `${"context"}.db`; const r = /^claim\\.intent\\.stage$/;',
                    "m.ts",
                ),
            ).map((entry) => entry.value),
        ).toEqual(["context.db", "context", ".db", "claim.intent.stage"]);
        expect(
            literalStrings(
                parseSource(
                    "const r = /^claim\\x2eintent\\u002estage$/; const s = /store\\.db/i;",
                    "m.ts",
                ),
            ).map((entry) => entry.value),
        ).toEqual(["claim.intent.stage", "store.db"]);
        expect(
            literalStrings(
                parseSource(
                    "const c = /^claim[.]intent[.]stage$/; const w = /mem[^.]+\\.sqlite/;",
                    "m.ts",
                ),
            ).map((entry) => entry.value),
        ).toEqual(["claim.intent.stage", "mem[^.]+.sqlite"]);
        expect(
            literalStrings(
                parseSource(
                    "const cls = /^[ck]laim[.]intent[.]stage$/; const range = /^[a-c][.]db$/; const wide = /^[a-zA-Z0-9_-]+$/;",
                    "m.ts",
                ),
            ).map((entry) => entry.value),
        ).toEqual([
            "claim.intent.stage",
            "klaim.intent.stage",
            "a.db",
            "b.db",
            "c.db",
            "[a-zA-Z0-9_-]+",
        ]);
        expect(
            literalStrings(
                parseSource("const hex = /^[0-9a-f]{7,12}$/; const run = /^[ab]+$/;", "m.ts"),
            ).map((entry) => entry.value),
        ).toEqual(["[0-9a-f]{7,12}", "[ab]+"]);
        expect(
            literalStrings(
                parseSource(
                    'const ctor = new RegExp("^claim[.]intent[.]stage$"); const call = RegExp("^STORE[.]DB$", "i"); const dyn = new RegExp(pattern);',
                    "m.ts",
                ),
            ).map((entry) => entry.value),
        ).toEqual([
            "claim.intent.stage",
            "^claim[.]intent[.]stage$",
            "STORE.DB",
            "store.db",
            "^STORE[.]DB$",
            "i",
        ]);
        expect(
            literalStrings(
                parseSource(
                    'const e = /^[\\x63]laim[.]intent$/; const f = "context".concat(".", "db");',
                    "m.ts",
                ),
            ).map((entry) => entry.value),
        ).toEqual(["claim.intent", "context.db", "context", ".", "db"]);
        expect(
            literalStrings(
                parseSource(
                    'const g = /^(?:claim\\.intent)(\\.stage)$/; const h = /(a|b)\\.db/; const l = "CONTEXT.DB".toLowerCase();',
                    "m.ts",
                ),
            ).map((entry) => entry.value),
        ).toEqual(["claim.intent.stage", "a.db", "b.db", "context.db", "CONTEXT.DB"]);
        expect(
            literalStrings(parseSource("const ci = /^CONTEXT[.]DB$/i;", "m.ts")).map(
                (entry) => entry.value,
            ),
        ).toEqual(["CONTEXT.DB", "context.db"]);
        expect(
            literalStrings(
                parseSource("const alt = /^(?:claim[.]intent[.]stage|kernel[.]read)$/;", "m.ts"),
            ).map((entry) => entry.value),
        ).toEqual(["claim.intent.stage", "kernel.read"]);
        expect(
            literalStrings(
                parseSource(
                    "const nested = /^(?:claim|kernel)[.](intent|read)$/; const esc = /a\\|b/;",
                    "m.ts",
                ),
            ).map((entry) => entry.value),
        ).toEqual(["claim.intent", "claim.read", "kernel.intent", "kernel.read", "a|b"]);
        expect(
            literalStrings(
                parseSource(
                    'const j = ["claim", "intent", "stage"].join("."); const k = ["a", b].join("");',
                    "m.ts",
                ),
            ).map((entry) => entry.value),
        ).toEqual(["claim.intent.stage", "claim", "intent", "stage", ".", "a"]);
        expect(
            literalStrings(
                parseSource(
                    [
                        'const full = prefix + ".intent.stage";',
                        'const prefix = head + "im";',
                        'const head = "cla";',
                        "const dynamic = runtime + prefix;",
                        "",
                    ].join("\n"),
                    "m.ts",
                ),
            ).map((entry) => entry.value),
        ).toEqual(["claim.intent.stage", ".intent.stage", "claim", "im", "cla"]);
        expect(
            literalStrings(
                parseSource(
                    [
                        'const prefix = "kernel";',
                        "{",
                        '    const prefix = "claim";',
                        '    const op = prefix + ".intent.stage";',
                        "}",
                        "",
                    ].join("\n"),
                    "m.ts",
                ),
            ).map((entry) => entry.value),
        ).toEqual([
            "kernel",
            "claim",
            "kernel.intent.stage",
            "claim.intent.stage",
            ".intent.stage",
        ]);
        expect(
            literalStrings(
                parseSource(
                    "const q = /^clai{1}m[.]intent[.]stage$/; const o = /^colou?r$/; const c = /^[ck]{1,2}laim$/; const r = /^a{2,3}$/;",
                    "m.ts",
                ),
            ).map((entry) => entry.value),
        ).toEqual([
            "claim.intent.stage",
            "color",
            "colour",
            "claim",
            "klaim",
            "cclaim",
            "cklaim",
            "kclaim",
            "kklaim",
            "aa",
            "aaa",
        ]);
        expect(
            literalStrings(
                parseSource("const g = /^(a|b){2}$/; const o = /^(ab)?x$/;", "m.ts"),
            ).map((entry) => entry.value),
        ).toEqual(["aa", "ab", "ba", "bb", "x", "abx"]);
        const negated = literalStrings(
            parseSource("const n = /^[^x]laim[.]intent[.]stage$/; const m = /^[^c]laim$/;", "m.ts"),
        ).map((entry) => entry.value);
        expect(negated).toContain("claim.intent.stage");
        expect(negated).not.toContain("claim");
        expect(negated.filter((value) => value.endsWith("laim")).length).toBeGreaterThan(1);
        const ten = "(a|b)".repeat(10);
        expect(literalStrings(parseSource(`const r = /^${ten}$/;`, "m.ts")).length).toBe(1024);
        expect(() => literalStrings(parseSource(`const r = /^${ten}(a|b)$/;`, "m.ts"))).toThrow(
            RangeError,
        );
    });

    // `RegExp.prototype.test` advances `lastIndex` for global and sticky patterns;
    // a stale offset skips a real literal on the next line and the scan passes vacuously.
    test("rejects a global pattern instead of under-counting", () => {
        expect(() => operationLiteralHits([file], /claim\./g)).toThrow(TypeError);
    });

    test("rejects a sticky pattern instead of under-counting", () => {
        expect(() => operationLiteralHits([file], /claim\./y)).toThrow(TypeError);
    });
});
