import type { PassRow } from "./rows";

/** Rows covering every outcome, a null service time, and both harnesses. */
export const WRITER_FIXTURE_ROWS: PassRow[] = [
    {
        harness: "opencode",
        tier: "10k",
        session: "opencode-10k-0",
        turn: 0,
        boundary_state: "cold",
        outcome: "completed",
        refusal: null,
        response_us: 41_250,
        service_us: 18_900,
        rss_bytes: 212_336_640,
        ipc_bytes: 1_572_864,
    },
    {
        harness: "opencode",
        tier: "s4_1m",
        session: "opencode-1m-0",
        turn: 7,
        boundary_state: "steady",
        outcome: "censored",
        refusal: null,
        response_us: 30_000_000,
        service_us: null,
        rss_bytes: 905_969_664,
        ipc_bytes: 1_605_632,
    },
    {
        harness: "pi",
        tier: "s3_100k",
        session: "pi-100k-1",
        turn: 3,
        boundary_state: "warming",
        outcome: "refused",
        refusal: "declined",
        response_us: 912,
        service_us: null,
        rss_bytes: 301_989_888,
        ipc_bytes: 0,
    },
    {
        harness: "pi",
        tier: "s4_1m",
        session: "pi-1m-2",
        turn: 1,
        boundary_state: "after_restart",
        outcome: "completed",
        refusal: null,
        response_us: 77_001,
        service_us: 50_123,
        rss_bytes: 1_073_741_824,
        ipc_bytes: 1_638_400,
    },
];
