//! The bundled SQLite engine is the oracle for effective terms: a scratch FTS5 table built from the contract's `fts5_table_args` stores analyzer output, and `fts5vocab` reports the terms the engine actually indexed per column.
//! Every expected term below is written by hand from the documented `unicode61` rules, never generated by the analyzer.

use std::num::NonZeroUsize;

use retrieval::lexical::{LexicalBounds, analyze, compile, fts5_table_args};
use rusqlite::{Connection, ToSql, params};

fn bounds() -> LexicalBounds {
    LexicalBounds {
        max_input_bytes: NonZeroUsize::new(4096).unwrap(),
        max_atoms: NonZeroUsize::new(256).unwrap(),
    }
}

fn engine() -> Connection {
    let conn = Connection::open_in_memory().unwrap();
    let options: Vec<String> = conn
        .prepare("PRAGMA compile_options")
        .unwrap()
        .query_map([], |row| row.get(0))
        .unwrap()
        .collect::<Result<_, _>>()
        .unwrap();
    assert!(
        options.iter().any(|option| option == "ENABLE_FTS5"),
        "the linked SQLite must carry FTS5: {options:?}"
    );
    conn.execute_batch(&format!(
        "CREATE VIRTUAL TABLE lexical USING fts5({});
         CREATE VIRTUAL TABLE lexical_terms USING fts5vocab('lexical', 'instance');",
        fts5_table_args()
    ))
    .unwrap();
    conn
}

/// Stores the analyzer's two column texts for `text` under `rowid`, the same path the index takes.
fn index(conn: &Connection, rowid: i64, text: &str) {
    let analysis = analyze(text, bounds()).unwrap();
    store(
        conn,
        rowid,
        &analysis.original_text(),
        &analysis.parts_text(),
    );
}

fn store(conn: &Connection, rowid: i64, original: &str, parts: &str) {
    conn.execute(
        "INSERT INTO lexical(rowid, original, parts) VALUES (?1, ?2, ?3)",
        params![rowid, original, parts],
    )
    .unwrap();
}

type Term = (String, i64, String, i64);

/// `(term, rowid, column, offset)` for every indexed term occurrence, in a fixed order.
fn effective_terms(conn: &Connection) -> Vec<Term> {
    conn.prepare("SELECT term, doc, col, offset FROM lexical_terms ORDER BY doc, col, offset")
        .unwrap()
        .query_map([], |row| {
            Ok((row.get(0)?, row.get(1)?, row.get(2)?, row.get(3)?))
        })
        .unwrap()
        .collect::<Result<_, _>>()
        .unwrap()
}

fn matches(conn: &Connection, expression: &dyn ToSql) -> Vec<i64> {
    conn.prepare("SELECT rowid FROM lexical WHERE lexical MATCH ?1 ORDER BY rowid")
        .unwrap()
        .query_map([expression], |row| row.get(0))
        .unwrap()
        .collect::<Result<_, _>>()
        .unwrap()
}

fn probe_matches(conn: &Connection, request: &str) -> Vec<Vec<i64>> {
    compile(&analyze(request, bounds()).unwrap())
        .iter()
        .map(|probe| matches(conn, probe))
        .collect()
}

fn row(term: &str, doc: i64, col: &str, offset: i64) -> Term {
    (term.to_string(), doc, col.to_string(), offset)
}

fn expected_terms() -> Vec<Term> {
    vec![
        row("httpserver", 1, "original", 0),
        row("snake_case", 1, "original", 1),
        row("x86_64", 1, "original", 2),
        row("http", 1, "parts", 0),
        row("server", 1, "parts", 1),
        row("snake", 1, "parts", 2),
        row("case", 1, "parts", 3),
        row("x", 1, "parts", 4),
        row("86", 1, "parts", 5),
        row("64", 1, "parts", 6),
        row("creme", 2, "original", 0),
        row("creme", 2, "original", 1),
        row("uber", 2, "original", 2),
        row("naive", 2, "original", 3),
        row("foo\u{E000}bar", 3, "original", 0),
        row("日本語", 3, "original", 1),
        row("ωmega", 3, "original", 2),
        row("e0308", 4, "original", 0),
        row("ids", 4, "original", 1),
        row("a", 4, "original", 2),
        row("2024", 4, "original", 3),
        row("01", 4, "original", 4),
        row("02", 4, "original", 5),
        row("e", 4, "parts", 0),
        row("0308", 4, "parts", 1),
    ]
}

const CORPUS: [(i64, &str); 5] = [
    (1, "HTTPServer snake_case x86_64"),
    (2, "crème cre\u{301}me Über naïve"),
    (3, "foo\u{E000}bar 日本語 Ωmega"),
    (4, "E0308 IDs a 2024-01-02"),
    (5, "!!! ..."),
];

#[test]
fn effective_terms_per_column_match_the_hand_written_expectation() {
    let conn = engine();
    for (rowid, text) in CORPUS {
        index(&conn, rowid, text);
    }
    assert_eq!(effective_terms(&conn), expected_terms());
}

#[test]
fn dropping_originals_fails_the_oracle() {
    let conn = engine();
    for (rowid, text) in CORPUS {
        let analysis = analyze(text, bounds()).unwrap();
        store(&conn, rowid, "", &analysis.parts_text());
    }
    let terms = effective_terms(&conn);
    assert_ne!(terms, expected_terms());
    assert!(!terms.contains(&row("httpserver", 1, "original", 0)));
    assert!(terms.contains(&row("http", 1, "parts", 0)));
}

#[test]
fn dropping_short_terms_fails_the_oracle() {
    let conn = engine();
    for (rowid, text) in CORPUS {
        let analysis = analyze(text, bounds()).unwrap();
        let long_atoms: Vec<&str> = analysis
            .atoms()
            .filter(|atom| atom.chars().count() >= 2)
            .collect();
        store(&conn, rowid, &long_atoms.join(" "), &analysis.parts_text());
    }
    let terms = effective_terms(&conn);
    assert_ne!(terms, expected_terms());
    let missing: Vec<Term> = expected_terms()
        .into_iter()
        .filter(|term| !terms.contains(term))
        .collect();
    assert_eq!(
        missing,
        [
            row("a", 4, "original", 2),
            row("2024", 4, "original", 3),
            row("01", 4, "original", 4),
            row("02", 4, "original", 5),
        ],
        "the one-character atom is gone and its neighbours shift by one offset"
    );
}

fn populated() -> Connection {
    let conn = engine();
    index(&conn, 1, "a b");
    index(&conn, 2, "OR");
    index(&conn, 3, "HTTPServer");
    index(&conn, 4, "HTTP Server");
    index(&conn, 5, "foobar");
    index(&conn, 6, "x86_64");
    index(&conn, 7, "NEAR");
    index(&conn, 8, "a");
    index(&conn, 9, "b");
    index(&conn, 10, "NOT");
    conn
}

#[test]
fn literal_operators_are_terms() {
    let conn = populated();
    assert_eq!(
        probe_matches(&conn, "a OR b"),
        [vec![1, 8], vec![2], vec![1, 9]]
    );
    assert_eq!(
        probe_matches(&conn, "a NOT b"),
        [vec![1, 8], vec![10], vec![1, 9]]
    );
    assert_eq!(
        probe_matches(&conn, "NEAR(a b)"),
        [vec![7], vec![1, 8], vec![1, 9]]
    );
}

#[test]
fn removing_the_quotes_makes_operators_operate() {
    let conn = populated();
    assert_eq!(
        matches(&conn, &"a OR b"),
        [1, 8, 9],
        "unquoted, OR unions a and b and the OR row is lost"
    );
    assert_eq!(
        matches(&conn, &"a NOT b"),
        [8],
        "unquoted, NOT removes rows and the NOT row is lost"
    );
    assert_eq!(
        matches(&conn, &"NEAR(a b)"),
        [1],
        "unquoted, NEAR constrains adjacency and the NEAR row is lost"
    );
}

#[test]
fn parts_extend_recall_without_implicit_expansion() {
    let conn = populated();
    assert_eq!(probe_matches(&conn, "HTTP"), [vec![3, 4]]);
    assert_eq!(probe_matches(&conn, "Server"), [vec![3, 4]]);
    assert_eq!(
        probe_matches(&conn, "HTTPServer"),
        [vec![3]],
        "a whole identifier never matches its separated words"
    );
    assert_eq!(probe_matches(&conn, "86"), [vec![6]]);
    assert_eq!(probe_matches(&conn, "x86_64"), [vec![6]]);
    assert_eq!(probe_matches(&conn, "x86"), [Vec::<i64>::new()]);
}

#[test]
fn no_prefix_expansion_and_the_prefix_control_differs() {
    let conn = populated();
    assert_eq!(probe_matches(&conn, "foo"), [Vec::<i64>::new()]);
    assert_eq!(
        matches(&conn, &"\"foo\"*"),
        [5],
        "the fallback control: a prefix operator would find foobar"
    );
}

#[test]
fn short_complete_terms_survive_broader_requests() {
    let conn = populated();
    assert_eq!(
        probe_matches(&conn, "a longer request mentions a"),
        [vec![1, 8], vec![], vec![], vec![], vec![1, 8]]
    );
}

#[test]
fn zero_atoms_issue_no_probe_while_a_nonempty_control_completes() {
    let conn = populated();
    assert_eq!(probe_matches(&conn, "!!! ... \"\""), Vec::<Vec<i64>>::new());
    assert_eq!(probe_matches(&conn, "b"), [vec![1, 9]]);
    assert_eq!(
        matches(&conn, &"\"\""),
        Vec::<i64>::new(),
        "an empty phrase matches nothing rather than everything"
    );
    let empty = conn
        .prepare("SELECT rowid FROM lexical WHERE lexical MATCH ?1")
        .unwrap()
        .query_map([""], |row| row.get::<_, i64>(0))
        .unwrap()
        .collect::<Result<Vec<_>, _>>();
    assert!(
        empty.is_err(),
        "an empty expression is an engine error, not a match-all"
    );
}

#[test]
fn folding_is_recall_only() {
    let conn = populated();
    index(&conn, 11, "Résumé");
    assert_eq!(probe_matches(&conn, "resume"), [vec![11]]);
    assert_eq!(probe_matches(&conn, "RÉSUMÉ"), [vec![11]]);
}

#[test]
fn a_mark_the_engine_separates_becomes_an_adjacent_pair_on_both_sides() {
    let conn = populated();
    index(&conn, 11, "x\u{305}y");
    index(&conn, 12, "x y");
    index(&conn, 13, "foo_x y_bar");
    assert_eq!(
        effective_terms(&conn)
            .into_iter()
            .filter(|(_, doc, _, _)| *doc == 11)
            .collect::<Vec<_>>(),
        [row("x", 11, "original", 0), row("y", 11, "original", 1)],
        "the analyzer keeps the run whole; the engine splits it into an adjacent pair"
    );
    assert_eq!(
        probe_matches(&conn, "x\u{305}y"),
        [vec![11, 12, 13]],
        "the probe is the same adjacent pair, so it also matches `x y` and the adjacent parts of `foo_x` and `y_bar`"
    );
    assert_eq!(
        probe_matches(&conn, "y x"),
        [vec![11, 12, 13], vec![6, 11, 12, 13]]
    );
}

#[test]
fn a_code_point_only_the_engine_knows_as_a_letter_is_still_analyzed_identically_on_both_sides() {
    let conn = populated();
    index(&conn, 11, "foo\u{1F914}bar");
    assert_eq!(
        effective_terms(&conn)
            .into_iter()
            .filter(|(_, doc, _, _)| *doc == 11)
            .collect::<Vec<_>>(),
        [row("foo", 11, "original", 0), row("bar", 11, "original", 1)],
        "the analyzer splits at the symbol before the engine sees the text"
    );
    store(&conn, 12, "foo\u{1F914}bar", "");
    assert_eq!(
        effective_terms(&conn)
            .into_iter()
            .filter(|(_, doc, _, _)| *doc == 12)
            .collect::<Vec<_>>(),
        [row("foo\u{1F914}bar", 12, "original", 0)],
        "raw text bypassing the analyzer would be one engine token"
    );
    assert_eq!(
        probe_matches(&conn, "foo\u{1F914}bar"),
        [vec![11], vec![11]]
    );
}

#[test]
fn an_atom_of_engine_separators_probes_for_an_empty_phrase_that_matches_nothing() {
    let conn = populated();
    index(&conn, 11, "\u{915}\u{93F}");
    assert_eq!(
        effective_terms(&conn)
            .into_iter()
            .filter(|(_, doc, _, _)| *doc == 11)
            .collect::<Vec<_>>(),
        [row("\u{915}", 11, "original", 0)],
        "the engine drops the vowel sign, so only the consonant is a term"
    );
    assert_eq!(probe_matches(&conn, "\u{93F}"), [Vec::<i64>::new()]);
    assert_eq!(probe_matches(&conn, "\u{915}\u{93F}"), [vec![11]]);
}
